services:
  neo4j:
    image: neo4j:4.4-enterprise
    container_name: neo4j
    volumes:
      - neo4jdata:/data
      - neo4jlogs:/logs
    environment:
      NEO4J_AUTH: neo4j/daccydac
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
    networks:
      - dac_dac
    ports:
      - "7474:7474"
      - "7687:7687"
  api:
    container_name: dac-api
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - "neo4j"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - dac_dac
    expose:
      - "7687"
    ports:
      - "5113:5113"
      - "8000:80"
networks:
  dac_dac:
    driver: bridge
volumes:
  neo4jdata:
  neo4jlogs: